config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :prospects
  get 'home/about'
  # root 'home#index'
  root 'prospects#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prospect.rb
class Prospect < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :prospects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :set_prospect, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /prospects or /prospects.json
  def index
    @prospects = Prospect.all
  end

  # GET /prospects/1 or /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    # @prospect = Prospect.new
    @prospect = current_user.prospects.build
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects or /prospects.json
  def create
    # @prospect = Prospect.new(prospect_params)
    @prospect = current_user.prospects.build(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to prospect_url(@prospect), notice: "Prospect was successfully created." }
        format.json { render :show, status: :created, location: @prospect }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1 or /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to prospect_url(@prospect), notice: "Prospect was successfully updated." }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1 or /prospects/1.json
  def destroy
    @prospect.destroy

    respond_to do |format|
      format.html { redirect_to prospects_url, notice: "Prospect was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @prospect = current_user.prospects.find_by(id: params[:id])
    redirect_to prospects_path, notice: "Not Authorized To Edit This Prospect" if @prospect.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prospect_params
      params.require(:prospect).permit(:first_name, :last_name, :company, :position, :address, :phone, :email, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/home/_header.html.erb
<br/>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "CRM App", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
        
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add Prospect", new_prospect_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <% else %>

        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
        <% end %>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<br/>
<h1>About Us...</h1>

app/views/home/index.html.erb
</br>
<h1>Hello World!</h1>
This is my first Rails webpage...

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>CRM App</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">

    <% if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/prospects/_form.html.erb
<%= form_with(model: prospect) do |form| %>
  <% if prospect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
        <% prospect.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name"%>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :company, class:"form-control", placeholder:"Company Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :position, class:"form-control", placeholder:"Position" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :address, class:"form-control", placeholder:"Address" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :prospect_user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/prospects/edit.html.erb
<h1>Editing Prospect</h1>

<%= render 'form', prospect: @prospect %>
<br/>
<%= link_to 'Show', @prospect, class:"btn btn-secondary" %>
<%= link_to 'Delete', @prospect, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<%= link_to 'Back', prospects_path, class:"btn btn-dark" %>

app/views/prospects/index.html.erb
<% if user_signed_in? %>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Position</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Email</th>
      <th>User ID</th>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @prospects.each do |prospect| %>
      <% if prospect.user == current_user %>
      <tr>
      <td>
      <%= link_to prospect.first_name + ' ' + prospect.last_name, prospect %>
      </td>

        <td><%= prospect.company %></td>
        <td><%= prospect.position %></td>
        <td><%= prospect.address %></td>
        <td><%= prospect.phone %></td>
        <td><%= prospect.email %></td>
        <td><%= prospect.user_id %></td>

        <td><%= link_to 'Delete', prospect, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prospect', new_prospect_path, class:"btn btn-secondary" %>
<% else %>

<h1>Hello World!</h1>
This is my first Rails webpage...

<% end %>

app/views/prospects/new.html.erb
<h1>Add New Prospect</h1>

<%= render 'form', prospect: @prospect %>
<br/>
<%= link_to 'Back', prospects_path, class:"btn btn-dark" %>

app/views/prospects/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
  <%= @prospect.first_name %>
  <%= @prospect.last_name %>
  </h1>
  <p class="lead">
    <%= @prospect.company %>  |
    <%= @prospect.position %>  |
    <%= @prospect.address %>  |
    <%= @prospect.phone %>  |
    <%= @prospect.email %>  |
  </p>
  <br/>
  <%= link_to 'Edit', edit_prospect_path(@prospect), class:"btn btn-secondary" %>
  <%= link_to 'Delete', @prospect, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
  <%= link_to 'Back', prospects_path, class:"btn btn-dark" %>